spads_username: spads
spads_user_password: "!"
# if running SPADS as root then user_homedir needs to be /root
user_homedir: /home/{{ spads_username }}
spads_install_path: "{{ user_homedir }}/spads"

# skips the tasks in the delete.yaml playbook if false as a safety mechanism
allow_delete: false

# Important: The URL's for engine releases contain %7B characters for brackets. It seems that wget does not always like these, so replace with {}
# Note that these characters get replaced with '.' characters for the engine_dir
engine_version_base: 2314-g9e0bf7d
engine_github_path: https://github.com/beyond-all-reason/spring/releases/download/spring_bar_{BAR105}105.1.1-2358-g9099868/spring_bar_.BAR105.105.1.1-2358-g9099868_linux-64-minimal-portable.7z
engine_dir: spring_bar_.BAR105.105.1.1-2358-g9099868_linux-64-minimal-portable

# allows to enable additonal services on the per-host basis
ufw_additional_profiles: []

package_dependencies:
  - acl
  - byobu
  - cpanminus
  - curl
  - g++
  - git
  - htop
  - libdbd-sqlite3-perl
  - libffi-platypus-perl
  - locate
  - lsof
  - make
  - mc
  - p7zip
  - p7zip-full
  - perl-doc
  - procps
  - python3-dev
  - python3-distutils
  - screen
  - sshpass
  - sudo
  - swig
  - tmux
  - ufw
  - wget

# the following are for spads_cluster_launcher.sh
spads_lobbyLogin:
spads_lobbyPassword:
spads_registrationEmail:
spads_lobbyHost:
spads_channel:
spads_baseGamePort: 53200
spads_baseAutoHostPort: 53100
spads_hostRegion: '"UNKNOWN - "'  # To be better defined in per group vars
spads_enginesBaseDir: "{{ spads_install_path }}/var/spring/"
spads_engineDir: "{{ engine_dir }}/"
spads_springDataDir: "{{ spads_install_path }}/var/spring/data"
spads_endGameCommandPath: "{{ spads_install_path }}/upload_replay.sh"
spads_localLanIp: 192.168.1.102
spads_maxInstances: 99
spads_targetSpares: 1
spads_clusters:
spads_hostIp:
spads_autoLoadPlugins: '"AutoRegister;ClusterManager;JsonStatus;InGameMute;DynamicMapRotation;BarManager;RatingManager"'

# the following are for spadsInstaller.auto
autoinstaller_release: unstable
autoinstaller_etcDir: etc
autoinstaller_varDir: var
autoinstaller_logDir: log
autoinstaller_springBinariesType: custom
autoinstaller_unitsyncPath: "{{ spads_install_path }}/var/spring/{{ engine_dir }}/libunitsync.so"
autoinstaller_baseDataDir: "{{ spads_install_path }}/var/spring/{{ engine_dir }}"
autoinstaller_mapModDataDir: "{{ spads_install_path }}/var/spring/"
autoinstaller_springServerType: dedicated
autoinstaller_springServer: "{{ spads_install_path }}/var/spring/{{ engine_dir }}/spring-dedicated"
autoinstaller_modName: "_NO_GAME_FOUND_"
autoinstaller_lobbyLogin: "[teh]cluster"
autoinstaller_lobbyPassword: changeme
autoinstaller_owner: changeme

mapSyncer_mqttBroker: broker.hivemq.com
